---
- hosts: "lb"
  remote_user: root
  gather_facts: yes
  connection: ssh

  tasks:

    - name: Ensure dependencies are installed
      apt: name={{ item }} state=present
      with_items:
        - haproxy
      when: ansible_os_family == "Debian"

    - name: Ensure haproxy conf is set
      template: 
        src: templates/haproxy.cfg.j2 
        dest: /etc/haproxy/haproxy.cfg

    - name: Ensure haproxy is started
      service:  
        name: haproxy
        state: started
        enabled: yes