---
- name: install shadowsocks
  hosts: server
  tasks:

    - name: apt update
      ansible.builtin.apt:
        update_cache: yes

    - name: install packages
      ansible.builtin.apt:
        name:
          - shadowsocks-libev
        state: present

    - name: Ensure shadowsocks conf is set
      template: 
        src: templates/ss.config.json.j2 
        dest: /etc/shadowsocks-libev/config.json

    - name: Ensure shadowsocks is started
      service:  
        name: shadowsocks-libev
        state: restarted
        enabled: yes
