---
- name: test
  hosts: server
  remote_user: root
  ansible_user: root
  tasks:
    - name: Ensure dependencies are installed
      apt: name={{ item }} state=present
      with_items:
        - nano
      when: ansible_os_family == "Debian"