name: loadbalancer
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Install Python"
        uses: actions/setup-python@v4
        with:
            python-version: "3.12"

      - name: "Install packages"
        shell: bash
        run: |
            python -m pip install ansible

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1
        with:
          host: 91.149.218.39
          username: root
          key: ${{ secrets.PRIVATE }}
          port: 22
          script: whoami

      # - name: connect
      #   shell: bash
      #   run: |
      #       ansible-playbook test.yaml -i hosts.yaml --key-file=${{ secrets.PRIVATE }}
      #   env:
      #     ANSIBLE_HOST_KEY_CHECKING: 'False'


          