name: loadbalancer
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Install Python"
        uses: actions/setup-python@v4
        with:
            python-version: "3.12"

      - name: "Install packages"
        shell: bash
        run: |
            python -m pip install ansible

      - name: sec
        shell: bash
        run: |
            echo $PASS > key
        env:
          PASS: ${{ secrets.PRIVATE}}

      - name: connect
        shell: bash
        run: |
            ansible-playbook test.yaml -i hosts.yaml --key-file=key
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'False'


          