name: loadbalancer
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # - uses: Hugozys/ansible-deploy@master
      #   with:
      #     directory: "."
      #     playbook: "nebula.yaml"
      #     ssh_key: ${{ secrets.PRIVATE }}
      #     ssh_key_file_name: id_rsa
          # verbose: "4"

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v3
        with:
          playbook: nebula.yaml
          directory: ./
          key: ${{secrets.PRIVATE}}
          options: |
            --inventory hosts.yaml
