name: loadbalancer
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Play Ansible Playbook
        uses: arillso/action.playbook@master
        with:
          playbook: test.yaml
          inventory: hosts.yaml
          galaxy_file: requirements.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'false'
          ANSIBLE_DEPRECATION_WARNINGS: 'false'