name: loadbalancer
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v3
        with:
          playbook: test.yaml
          inventory: |
            [server]
            91.149.218.39 ansible_user: root
          key: ${{secrets.SSH_PRIVATE_KEY}}
