name: loadbalancer
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v3
        with:
          playbook: test.yaml
          inventory: |
            [server]
            srv1 ansible_ssh_host=91.149.218.39 ansible_ssh_port=22 ansible_ssh_user=root keepalived_priority=100
          key: ${{secrets.SSH_PRIVATE_KEY}}
