name: loadbalancer
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Install Python"
        uses: actions/setup-python@v4
        with:
            python-version: "3.12"

      - name: "Install packages"
        shell: bash
        run: |
            python -m pip install ansible

      - name: "Print Ansible version"
        run: echo $APASS
        env:
          APASS: ${{ secrets.PASSWORD }}