name: loadbalancer
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Hugozys/ansible-deploy@master
        with:
          directory: "."
          playbook: "test.yaml"
          ssh_key: ${{secrets.PRIVATE}}
          ssh_key_file_name: secret_id_rsa
          verbose: "4"