name: loadbalancer
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: sec
        shell: bash
        run: |
            eval $(ssh-agent -s)
            echo "${{ secrets.PRIVATE}}" | tr -d '\r' | ssh-add -
            mkdir -p ~/.ssh
            chmod 700 ~/.ssh
            ssh-keyscan 91.149.218.39 >> ~/.ssh/known_hosts
            chmod 644 ~/.ssh/known_hosts
            cat ~/.ssh/known_hosts
        env:
          PASS: ${{ secrets.PRIVATE}}

      # - uses: Hugozys/ansible-deploy@master
      #   with:
      #     directory: "."
      #     playbook: "test.yaml"
      #     ssh_key: ${{secrets.PRIVATE}}
      #     ssh_key_file_name: id_rsa
      #     verbose: "4"