name: loadbalancer
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Install Python"
        uses: actions/setup-python@v4
        with:
            python-version: "3.12"

      - name: "Install packages"
        shell: bash
        run: |
            python -m pip install ansible

      - name: "Install ssl"
        run: |
            sudo apt install openssh-client -y

      - name: "ssh"
        run: |
            eval $(ssh-agent -s)
            echo "${{ secrets.PRIVATE }}" | tr -d '\r' | ssh-add -
            mkdir -p ~/.ssh
            chmod 700 ~/.ssh
            ssh-keyscan 91.149.218.39 >> ~/.ssh/known_hosts
            chmod 644 ~/.ssh/known_hosts

      - name: connect
        shell: bash
        run: |
            ansible-playbook test.yaml -i hosts.yaml
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'False'


          