name: loadbalancer
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # - name: Play Ansible Playbook
      #   uses: arillso/action.playbook@master
      #   with:
      #     playbook: test.yaml
      #     inventory: hosts.yaml
      #     private_key: ${{ secrets.KEY }}
      #   env:
      #     ANSIBLE_HOST_KEY_CHECKING: 'false'
      #     ANSIBLE_DEPRECATION_WARNINGS: 'false'
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v3
        with:
          # Required, playbook filepath
          playbook: test.yaml
          # Optional, directory where playbooks live
          directory: ./
          inventory: |
            [server]
            91.149.218.39

          # Optional, SSH known hosts file content
          known_hosts: ${{ secrets.PUB }}