name: loadbalancer
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Perform ansible playbook to deploy
        uses: actions-ansible@v2
        with:
          playbook: ./test.yaml
          inventory: ./hosts.yaml