name: loadbalancer
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Install Python"
        uses: actions/setup-python@v4
        with:
            python-version: "3.12"

      - name: "Install packages"
        shell: bash
        run: |
            python -m pip install ansible

      - name: Pass
        shell: bash
        run: |
            touch pass.txt && printenv $APASS > pass.txt && cat pass.txt
        env:
          APASS: ${{ secrets.PASSWORD }}

      - name: connect
        shell: bash
        run: |
            ansible-playbook test.yaml -i hosts.yaml --conn-pass-file=pass.txt
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'False'