name: loadbalancer
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Install Ansible"
        uses: alex-oleshkevich/setup-ansible@VERSION 
        with:
          version: "9.3.0"

      - name: "Print Ansible version"
        run: echo $APASS
        env:
          APASS: ${{ secrets.PASSWORD }}